language: node_js
node_js:
  - 8.11.1
before_script: cd ./client && npm install
before_script: cd ./server && npm install
cache:
  directories:
  - node_modules
  - client/node_modules
  - server/node_modules
script:
  - "npm run test"