language: node_js
node_js:
- 8.11.1
install:
- cd functions
- npm install
- cd ..
- npm install
cache:
  directories:
  - node_modules
  - functions/node_modules
after_success:
- echo $REACT_APP_ENV
- pwd
- ls
- ./node_modules/.bin/firebase deploy --token $FIREBASE_FUNCTIONS_CONTAINER_TOKEN
notifications:
  email: false