version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file: ./.env
  functions:
    build: ./functions
    command: firebase serve --only functions --host 0.0.0.0 --token ${FIREBASE_FUNCTIONS_CONTAINER_TOKEN}
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    env_file: ./.env