version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file: ./.env
    depends_on:
      - functions
  functions:
    build: ./functions
    command: ./node_modules/firebase-tools/bin/firebase serve --only functions --host 0.0.0.0 --token ${FIREBASE_TOKEN}
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    env_file: ./.env