version: '2'
services:
  web:
    build: ./client
    command: npm run start
    volumes:
      - ./client:/usr/src/client/
      - /usr/src/client/node_modules
    ports:
      - "3000:3000"
    env_file: ./.env
    depends_on:
      - server
  # webhook:
  #   build: ./webhook
  #   command: ultrahook -k Lv9Lpl22HXUMp7YWHXBOKfxKEaJl29zQ plaidWebHook http://localhost:5000/api/plaidWebHook
  #   volumes:
  #     - .:/usr/src/app/
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "5001:5001"
  server:
    build: .
    command: npm run develop
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
      - ~/.config/:/root/.config
    ports:
      - "5000:5000"
    env_file: ./.env