version: '2'
services:
  client:
    build: ./client
    command: npm run start
    volumes:
      - ./client:/usr/src/client/
      - /usr/src/client/node_modules
    ports:
      - "3000:3000"
    env_file: ./client/.env
    depends_on:
      - server
  server:
    build: ./server
    command: npm run develop
    volumes:
      - ./server:/usr/src/app/
      - /usr/src/app/node_modules
      - ~/.config/:/root/.config
    ports:
      - "5000:5000"
    env_file: ./server/.env