[ { account_id: 'k7jl4aaJ4MSwxbpZ5aNgCeoAMezgWGHW9qnn3',
    account_owner: null,
    amount: 12,
    category: [ 'Food and Drink', 'Restaurants' ],
    category_id: '13005000',
    date: '2018-08-21',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: '3322',
       zip: null },
    name: 'McDonald\'s',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'bBQMqll8qDcjAMbvmqKgUK6dWZ487VtVlEje6',
    transaction_type: 'place',
    unofficial_currency_code: null },
  { account_id: 'k7jl4aaJ4MSwxbpZ5aNgCeoAMezgWGHW9qnn3',
    account_owner: null,
    amount: 4.33,
    category: [ 'Food and Drink', 'Restaurants', 'Coffee Shop' ],
    category_id: '13005043',
    date: '2018-08-21',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'Starbucks',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'mQZKPNNrPMHAa5X9mWRlCNRz8D1bEVfLE9Nae',
    transaction_type: 'place',
    unofficial_currency_code: null },
  { account_id: 'k7jl4aaJ4MSwxbpZ5aNgCeoAMezgWGHW9qnn3',
    account_owner: null,
    amount: 89.4,
    category: [ 'Food and Drink', 'Restaurants' ],
    category_id: '13005000',
    date: '2018-08-20',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'SparkFun',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'yGz7pggApkH1nZqkVKNmidavozxEZWFyGomBn',
    transaction_type: 'place',
    unofficial_currency_code: null },
  { account_id: 'le5kN44qNmSQd57pL1PBfvKm7vjeP5iZ4nQQz',
    account_owner: null,
    amount: -4.22,
    category: [ 'Food and Drink', 'Restaurants' ],
    category_id: '13005000',
    date: '2018-08-19',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'INTRST PYMNT',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'DPjevWWxvnF3eaBwkGLJugAzXePmbKtv17DMg',
    transaction_type: 'place',
    unofficial_currency_code: null },
  { account_id: 'K19omBBpmAteznWZ8KDEt1w5X13NL8CVyKqq6',
    account_owner: null,
    amount: 500,
    category: [ 'Travel', 'Airlines and Aviation Services' ],
    category_id: '22001000',
    date: '2018-08-09',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'United Airlines',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: '5vGljNNLjnC5n1gZoGvpfolJbdDaMxSZvblmw',
    transaction_type: 'special',
    unofficial_currency_code: null },
  { account_id: 'k7jl4aaJ4MSwxbpZ5aNgCeoAMezgWGHW9qnn3',
    account_owner: null,
    amount: 6.33,
    category: [ 'Travel', 'Car Service', 'Ride Share' ],
    category_id: '22006001',
    date: '2018-08-07',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'Uber 072515 SF**POOL**',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: '9qNzZeeGZRS9gEwQ6KrJFLzRqymbjdCRrk16x',
    transaction_type: 'special',
    unofficial_currency_code: null },
  { account_id: 'K19omBBpmAteznWZ8KDEt1w5X13NL8CVyKqq6',
    account_owner: null,
    amount: 500,
    category: [ 'Food and Drink', 'Restaurants' ],
    category_id: '13005000',
    date: '2018-08-04',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'Tectra Inc',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'JMRpmzz1mwIErRB4vJoqtDbokjJV6xtdA13Pj',
    transaction_type: 'place',
    unofficial_currency_code: null },
  { account_id: 'K19omBBpmAteznWZ8KDEt1w5X13NL8CVyKqq6',
    account_owner: null,
    amount: 2078.5,
    category: [ 'Payment' ],
    category_id: '16000000',
    date: '2018-08-03',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'AUTOMATIC PAYMENT - THANK',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'qLp3QeeNQJF8Jq6RLmrZcmwdjzMJGyfdELG35',
    transaction_type: 'special',
    unofficial_currency_code: null },
  { account_id: 'K19omBBpmAteznWZ8KDEt1w5X13NL8CVyKqq6',
    account_owner: null,
    amount: 500,
    category: [ 'Food and Drink', 'Restaurants' ],
    category_id: '13005000',
    date: '2018-08-03',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'KFC',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'le5kN44qNmSQd57pL1PBfvK6B5dxDptZ4nQxx',
    transaction_type: 'place',
    unofficial_currency_code: null },
  { account_id: 'K19omBBpmAteznWZ8KDEt1w5X13NL8CVyKqq6',
    account_owner: null,
    amount: 500,
    category: [ 'Shops', 'Bicycles' ],
    category_id: '19007000',
    date: '2018-08-03',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'Madison Bicycle Shop',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'k7jl4aaJ4MSwxbpZ5aNgCeoK7GaJ1xtW9qnvn',
    transaction_type: 'place',
    unofficial_currency_code: null },
  { account_id: 'le5kN44qNmSQd57pL1PBfvKm7vjeP5iZ4nQQz',
    account_owner: null,
    amount: 25,
    category: [ 'Payment', 'Credit Card' ],
    category_id: '16001000',
    date: '2018-07-25',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'CREDIT CARD 3333 PAYMENT *//',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'VbG39QQl9Zt7eNxmJrW8tQZoWkV6E7HWao1ra',
    transaction_type: 'special',
    unofficial_currency_code: null },
  { account_id: 'k7jl4aaJ4MSwxbpZ5aNgCeoAMezgWGHW9qnn3',
    account_owner: null,
    amount: 5.4,
    category: [ 'Travel', 'Car Service', 'Ride Share' ],
    category_id: '22006001',
    date: '2018-07-25',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'Uber 063015 SF**POOL**',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'vE9NkLLpkgUneDkBaWdbhx5jdMN1GeiWpgmdQ',
    transaction_type: 'special',
    unofficial_currency_code: null },
  { account_id: 'rpyxZQQjZ7t4jqmLpgzeCjNJBjnApetlQp44l',
    account_owner: null,
    amount: 5850,
    category: [ 'Transfer', 'Debit' ],
    category_id: '21006000',
    date: '2018-07-24',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'ACH Electronic CreditGUSTO PAY 123456',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: 'ACH',
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'rpyxZQQjZ7t4jqmLpgzeCjN8leM79LclQp4zL',
    transaction_type: 'special',
    unofficial_currency_code: null },
  { account_id: 'qLp3QeeNQJF8Jq6RLmrZcmwpLmZQDzfdELGG8',
    account_owner: null,
    amount: 1000,
    category: [ 'Service' ],
    category_id: '18000000',
    date: '2018-07-24',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'CD DEPOSIT .INITIAL.',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'wW9PoppgoRIw16mXPqaAC4r7vbJ19XirG3w8p',
    transaction_type: 'place',
    unofficial_currency_code: null },
  { account_id: 'K19omBBpmAteznWZ8KDEt1w5X13NL8CVyKqq6',
    account_owner: null,
    amount: 78.5,
    category: [ 'Recreation', 'Gyms and Fitness Centers' ],
    category_id: '17018000',
    date: '2018-07-23',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'Touchstone Climbing',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'K19omBBpmAteznWZ8KDEt1wbG8zPevFVyKqQ7',
    transaction_type: 'place',
    unofficial_currency_code: null },
  { account_id: 'k7jl4aaJ4MSwxbpZ5aNgCeoAMezgWGHW9qnn3',
    account_owner: null,
    amount: -500,
    category: [ 'Travel', 'Airlines and Aviation Services' ],
    category_id: '22001000',
    date: '2018-07-23',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'United Airlines',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'RWXK9PPR9wIwNGalWX1qCNZ3bjqypgfR9wyEg',
    transaction_type: 'special',
    unofficial_currency_code: null },
  { account_id: 'k7jl4aaJ4MSwxbpZ5aNgCeoAMezgWGHW9qnn3',
    account_owner: null,
    amount: 12,
    category: [ 'Food and Drink', 'Restaurants' ],
    category_id: '13005000',
    date: '2018-07-22',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: '3322',
       zip: null },
    name: 'McDonald\'s',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: '6RNq7PPo7nFn6yrqVgoDhWqXk7RaLZcg6mZ5R',
    transaction_type: 'place',
    unofficial_currency_code: null },
  { account_id: 'k7jl4aaJ4MSwxbpZ5aNgCeoAMezgWGHW9qnn3',
    account_owner: null,
    amount: 4.33,
    category: [ 'Food and Drink', 'Restaurants', 'Coffee Shop' ],
    category_id: '13005043',
    date: '2018-07-22',
    iso_currency_code: 'USD',
    location:
     { address: null,
       city: null,
       lat: null,
       lon: null,
       state: null,
       store_number: null,
       zip: null },
    name: 'Starbucks',
    payment_meta:
     { by_order_of: null,
       payee: null,
       payer: null,
       payment_method: null,
       payment_processor: null,
       ppd_id: null,
       reason: null,
       reference_number: null },
    pending: false,
    pending_transaction_id: null,
    transaction_id: 'XyEd9MMz9bHRZKnWeogxS83MLgXmepcdQ9ZaW',
    transaction_type: 'place',
    unofficial_currency_code: null } ]